# Generated by Django 2.1.7 on 2019-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='student',
        ),
        migrations.DeleteModel(
            name='mentor',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
